#!/bin/sh
# SPFN Mobile — proof that a run cannot start against a host the app may not reach.
#
#   sh tools/harness/probe-cleartext-host.sh
#
# The Android harness app is allowed to talk plain HTTP to exactly ONE host. That host is
# written into a network security config by the build, out of the local.properties key
# `spfn.harness.serverBaseUrl`, and the address run-harness.sh hands the app comes from
# somewhere else entirely — the port the reference server bound. Nothing held the two
# together, and on the 2d run they disagreed: the runner rewrote the address to the
# emulator's alias for the host loopback while the build permitted a LAN address, ten of
# twelve cells came back err:connectivity, and the two that passed were the two that never
# call anything. A wrong answer shaped like a flow bug.
#
# The alias is gone since 2f — every Android target reaches the host through `adb reverse`
# and the app is handed `http://127.0.0.1:<port>` — so a run's own host is loopback. The
# guard stays: the key is hand-written per machine, and a checkout configured for a LAN
# server is exactly the disagreement above with the two addresses swapped.
#
# So the runner now compares them after the build and before the first flow. That check is
# new code guarding a run, which is exactly the code worth doubting, so this probe drives
# `cleartext_permits` from the runner itself against every shape the pair can take:
#
#   the config names the host the app gets          -> permitted
#   the config names a different host               -> refused
#   the config names no host at all                 -> refused
#   the config file is missing                      -> refused; unread is not checked
#   the URL carries a port, the config never does   -> permitted
#
# The function is EXTRACTED from run-harness.sh rather than copied here. A copy would go
# on passing after the original changed, which is the failure mode a probe exists to
# prevent. tools/harness/probe-receipts.sh does the same for receipt derivation.

set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
RUNNER="$ROOT/tools/harness/run-harness.sh"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT INT TERM

sed -n '/^cleartext_hosts()/,/^}/p' "$RUNNER" > "$WORK/guard.sh"
sed -n '/^url_host()/,/^}/p' "$RUNNER" >> "$WORK/guard.sh"
sed -n '/^cleartext_permits()/,/^}/p' "$RUNNER" >> "$WORK/guard.sh"
# shellcheck source=/dev/null
. "$WORK/guard.sh"

for FUNCTION in cleartext_hosts url_host cleartext_permits
do
    if ! command -v "$FUNCTION" > /dev/null 2>&1
    then
        printf 'FAIL  %s could not be extracted from run-harness.sh\n' "$FUNCTION"
        printf '      the probe cannot pass by failing to find what it tests\n'
        exit 1
    fi
done

# The file the build really writes, in its three shapes. The generator assembles it line by
# line and asserts its own domain count, so these are its output and not an approximation
# of it — tools/harness/android/build.gradle.kts holds the writer.
config()
{
    printf '<?xml version="1.0" encoding="utf-8"?>\n' > "$1"
    printf '<!-- GENERATED by :harness-android:generateHarnessNetworkSecurityConfig. Do not edit. -->\n' >> "$1"
    printf '<network-security-config>\n' >> "$1"
    printf '    <base-config cleartextTrafficPermitted="false" />\n' >> "$1"
    if [ -n "$2" ]
    then
        printf '    <domain-config cleartextTrafficPermitted="true">\n' >> "$1"
        printf '        <domain includeSubdomains="false">%s</domain>\n' "$2" >> "$1"
        printf '    </domain-config>\n' >> "$1"
    fi
    printf '</network-security-config>\n' >> "$1"
}

config "$WORK/loopback.xml" 127.0.0.1
config "$WORK/alias.xml" 10.0.2.2
config "$WORK/lan.xml" 10.67.210.235
config "$WORK/nothing.xml" ''

STATUS=0

check()
{
    if cleartext_permits "$2" "$3"
    then
        ACTUAL=permitted
    else
        ACTUAL=refused
    fi

    if [ "$ACTUAL" = "$4" ]
    then
        printf 'ok    %-34s -> %s\n' "$1" "$ACTUAL"
    else
        printf 'FAIL  %-34s -> %s, expected %s\n' "$1" "$ACTUAL" "$4"
        STATUS=1
    fi
}

printf 'SPFN Mobile — the cleartext host guard, probed\n\n'

# Every Maestro run — emulator and phone alike — reaches the host through `adb reverse` and
# is handed the loopback address, so this is the shape a correctly configured checkout has.
check 'a Maestro run behind adb reverse' "$WORK/loopback.xml" 'http://127.0.0.1:8080' permitted
# The 2d run, in one line: the runner rewrote the base URL to the emulator's alias and the
# build permitted a LAN address. Every cell that touches the network paid for it. The
# alias is no longer handed to any app, but the guard is what makes that a refusal rather
# than twelve cells of err:connectivity.
check 'the LAN config the 2d run had' "$WORK/lan.xml" 'http://10.0.2.2:8080' refused
# A checkout left configured for a LAN server is the same disagreement the other way round:
# the runner hands the app loopback and the build permits an address the app may not reach.
check 'a LAN config against a loopback run' "$WORK/lan.xml" 'http://127.0.0.1:8080' refused
check 'a LAN config with the LAN address' "$WORK/lan.xml" 'http://10.67.210.235:8080' permitted
# The emulator's alias is a host like any other to a network security config: a build that
# still names it does not permit the loopback address a 2f run hands the app.
check 'the alias config a 2d checkout has' "$WORK/alias.xml" 'http://127.0.0.1:8080' refused
check 'a config that permits nothing' "$WORK/nothing.xml" 'http://127.0.0.1:8080' refused
check 'no config file at all' "$WORK/absent.xml" 'http://127.0.0.1:8080' refused
# The two spellings of loopback are different hosts to a network security config —
# 127.0.0.1 is permitted by a config naming 127.0.0.1 and by nothing else.
check 'localhost against 127.0.0.1' "$WORK/loopback.xml" 'http://localhost:8080' refused
# The URL the runner hands the app always carries a port and the config never does, so a
# comparison that kept the port would refuse every correctly configured run.
check 'a port the config cannot name' "$WORK/loopback.xml" 'http://127.0.0.1:53211' permitted
# An address nothing can be read out of is refused, not silently matched against the
# nothing the config would then also hold.
check 'a base URL with no host' "$WORK/loopback.xml" '' refused

printf '\n'
if [ "$STATUS" -eq 0 ]
then
    printf 'RESULT: PASS\n'
    exit 0
fi
printf 'RESULT: FAIL\n'
exit 1
