// SPFN Mobile — generated client conformance, Swift half of the parity gate.
//
// Every assertion here runs against generated code. If the generator changed shape, or
// the bundle changed and the clients were not regenerated, this suite is what notices.

import Foundation
import SPFNCore
import SPFNGenerated
import XCTest

final class OperationConformanceTests: XCTestCase
{
    func testGeneratedBindingMatchesTheLock() throws
    {
        let lock = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/upstream.lock.json")))
        ).members()
        let contract = try lock["contract"]!.members()

        XCTAssertEqual(SPFNGeneratedContract.binding.importedVersion, try contract.text("version"))
        XCTAssertEqual(SPFNGeneratedContract.binding.importedManifestSha256, try contract.text("manifestSha256"))
        XCTAssertEqual(SPFNGeneratedContract.binding.supportedRange, try contract.text("supportedRange"))
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMajor), try contract.number("major"))
        // The 0.x compatibility rule is decided from the major and the minor together,
        // so a generated binding that carried only the major would silently accept a
        // neighbouring minor the lock excludes.
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMinor), try contract.number("minor"))
    }

    func testGeneratedBindingDigestMatchesTheBundleOnDisk() throws
    {
        let bundle = try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json"))
        XCTAssertEqual(
            SPFNDigest.sha256Hex([UInt8](bundle)),
            SPFNGeneratedContract.binding.importedManifestSha256,
            "the generated header claims a digest the bundle does not have"
        )
    }

    /// The mirror of what this assertion used to say. While the bundle was hand-authored
    /// here, the test insisted the build must NOT claim an upstream export. The bundle is
    /// now generated by SPFN primitives, so the same question has the opposite answer —
    /// and it still has to be asked, because the origin string is what every consumer
    /// reads to decide whether the contract was verified against a server or against
    /// this repository's own opinion of one.
    func testTheBundleIsClaimedToBeAnUpstreamExport() throws
    {
        XCTAssertTrue(
            SPFNGeneratedContract.binding.isUpstreamExport,
            "the pinned bundle is an SPFN primitives export; a build that reports otherwise is reading a stale generated source"
        )
        XCTAssertEqual(SPFNGeneratedContract.binding.origin, "spfn-primitives-ci-export")
    }

    func testOperationDescriptorsMatchTheBundle() throws
    {
        let bundle = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json")))
        ).members()

        let declared = try bundle.list("operations").map { try $0.members() }
        XCTAssertEqual(SPFNGeneratedOperations.all.count, declared.count)

        for entry in declared
        {
            let id = try entry.text("id")
            let operation = try XCTUnwrap(SPFNGeneratedOperations.operation(id: id), "\(id) was not generated")
            XCTAssertEqual(operation.method, try entry.text("method"))
            XCTAssertEqual(operation.path, try entry.text("path"))
            XCTAssertEqual(operation.authProfile, "clientProofV1")
        }

        XCTAssertNil(SPFNGeneratedOperations.operation(id: "no.such.operation"))
    }

    func testRequestVectorsCanonicalizeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let requests = try fixture.list("requests")
        XCTAssertFalse(requests.isEmpty)

        for request in requests
        {
            let entry = try request.members()
            let name = try entry.text("name")
            let canonical = try roundTrip(type: try entry.text("type"), value: entry["value"]!)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical request bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical request digest differs for '\(name)'"
            )
        }
    }

    func testResponseVectorsDecodeAndReEncodeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let responses = try fixture.list("responses")
        XCTAssertFalse(responses.isEmpty)

        for response in responses
        {
            let entry = try response.members()
            let name = try entry.text("name")
            let wire = try SPFNCanonicalJSON.parse(try entry.text("wire"))
            let canonical = try roundTrip(type: try entry.text("type"), value: wire)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical response bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical response digest differs for '\(name)'"
            )
        }
    }

    /// The generated binding must refuse exactly what its own range excludes. The
    /// contract line is 0.x, so the neighbouring minor is a breaking change and not an
    /// additive one — this used to pass a 1.4.0 server because only majors were compared.
    func testAContractOutsideTheDeclaredRangeIsAnUpgradeError() throws
    {
        let binding = SPFNGeneratedContract.binding
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: binding.importedVersion))

        for version in ["0.2.0", "1.0.0", "1.4.0", "2.0.0"]
        {
            XCTAssertThrowsError(try binding.requireSupported(serverContractVersion: version))
            { error in
                guard case SPFNDecodingError.unsupportedContractVersion(let found, let range) = error
                else
                {
                    return XCTFail("expected an upgrade error, got \(error)")
                }
                XCTAssertEqual(found, version)
                XCTAssertEqual(range, binding.admittedRange)
                // This pin is a release, so the two agree here. The assertion is on the
                // admitted range because that is what the refusal is obliged to name.
                XCTAssertEqual(binding.admittedRange, binding.supportedRange)
            }
        }
    }

    /// Decodes a fixture value into the generated type it names, then re-encodes it.
    /// The switch is the one place a test has to know the contract's type names.
    private func roundTrip(type: String, value: SPFNCanonicalValue) throws -> SPFNCanonicalValue
    {
        switch type
        {
        case "HandshakeRequest":
            return try SPFNHandshakeRequest(canonical: value).canonicalValue
        case "HandshakeResponse":
            return try SPFNHandshakeResponse(canonical: value).canonicalValue
        case "EchoRequest":
            return try SPFNEchoRequest(canonical: value).canonicalValue
        case "EchoResponse":
            return try SPFNEchoResponse(canonical: value).canonicalValue
        case "ListItemsRequest":
            return try SPFNListItemsRequest(canonical: value).canonicalValue
        case "ListItemsResponse":
            return try SPFNListItemsResponse(canonical: value).canonicalValue
        default:
            XCTFail("fixture names an unknown type '\(type)'")
            throw ConformanceFailure.shape
        }
    }
}
