// SPFN Mobile — generated client conformance, Swift half of the parity gate.
//
// Every assertion here runs against generated code. If the generator changed shape, or
// the bundle changed and the clients were not regenerated, this suite is what notices.

import Foundation
import SPFNCore
import SPFNGenerated
import XCTest

final class OperationConformanceTests: XCTestCase
{
    func testGeneratedBindingMatchesTheLock() throws
    {
        let lock = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/upstream.lock.json")))
        ).members()
        let contract = try lock["contract"]!.members()

        XCTAssertEqual(SPFNGeneratedContract.binding.importedVersion, try contract.text("version"))
        XCTAssertEqual(SPFNGeneratedContract.binding.importedManifestSha256, try contract.text("manifestSha256"))

        // Codegen reads this range from the lock rather than from the bundle, so the
        // binding states the window this SDK admits and not the line upstream declares.
        // The two differ from 0.4.1 on: the bundle says ">=0.4.0 <0.5.0" because that is
        // the line, while the lock says ">=0.4.1 <0.5.0" because 0.4.1 added operations
        // a 0.4.0 server does not serve.
        XCTAssertEqual(SPFNGeneratedContract.binding.supportedRange, try contract.text("supportedRange"))
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMajor), try contract.number("major"))
        // The 0.x compatibility rule is decided from the major and the minor together,
        // so a generated binding that carried only the major would silently accept a
        // neighbouring minor the lock excludes.
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMinor), try contract.number("minor"))
    }

    func testGeneratedBindingDigestMatchesTheBundleOnDisk() throws
    {
        let bundle = try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json"))
        XCTAssertEqual(
            SPFNDigest.sha256Hex([UInt8](bundle)),
            SPFNGeneratedContract.binding.importedManifestSha256,
            "the generated header claims a digest the bundle does not have"
        )
    }

    /// The mirror of what this assertion used to say. While the bundle was hand-authored
    /// here, the test insisted the build must NOT claim an upstream export. The bundle is
    /// now generated by SPFN primitives, so the same question has the opposite answer —
    /// and it still has to be asked, because the origin string is what every consumer
    /// reads to decide whether the contract was verified against a server or against
    /// this repository's own opinion of one.
    func testTheBundleIsClaimedToBeAnUpstreamExport() throws
    {
        XCTAssertTrue(
            SPFNGeneratedContract.binding.isUpstreamExport,
            "the pinned bundle is an SPFN primitives export; a build that reports otherwise is reading a stale generated source"
        )
        XCTAssertEqual(SPFNGeneratedContract.binding.origin, "spfn-primitives-ci-export")
    }

    func testOperationDescriptorsMatchTheBundle() throws
    {
        let bundle = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json")))
        ).members()

        let declared = try bundle.list("operations").map { try $0.members() }
        XCTAssertEqual(SPFNGeneratedOperations.all.count, declared.count)

        for entry in declared
        {
            let id = try entry.text("id")
            let operation = try XCTUnwrap(SPFNGeneratedOperations.operation(id: id), "\(id) was not generated")
            XCTAssertEqual(operation.method, try entry.text("method"))
            XCTAssertEqual(operation.path, try entry.text("path"))
            XCTAssertEqual(operation.authProfile, try entry.text("authProfile"))
            XCTAssertEqual(operation.requiresSession, try entry.bool("requiresSession"))

            // Every declared auth class resolves to a generated case; the generated
            // type is what lets the execute path fail closed on anything else.
            XCTAssertNotNil(
                SPFNGeneratedOperations.authClass(of: operation),
                "\(id) names an auth class the generated enum does not carry"
            )
        }

        XCTAssertNil(SPFNGeneratedOperations.operation(id: "no.such.operation"))
    }

    // MARK: - The operation table

    /// One row of the contract's `operations` array, transcribed by hand.
    ///
    /// Written from `Contracts/spfn-mobile-contract.json` read as text, not produced from
    /// the bundle at run time and not read out of the generated sources: a table derived
    /// from either of the things it checks proves only that they agree with themselves.
    struct DeclaredOperation
    {
        let id: String
        let method: String
        let path: String
        let authProfile: String
        let requiresSession: Bool
        let since: String
        let requestType: String?
        let responseType: String?
    }

    /// The sixteen operations contract 0.10.0 declares, in bundle order. The last five
    /// arrived with 0.10.0; `auth.device.deny` is the one that names no response type,
    /// which `restOperations.responseBody` defines as answering 204 with an empty body.
    static let declaredOperations: [DeclaredOperation] = [
        DeclaredOperation(id: "core.time", method: "GET", path: "/_core/time", authProfile: "none", requiresSession: false, since: "0.9.0", requestType: nil, responseType: "ServerTimeResponse"),
        DeclaredOperation(id: "auth.clientProof.handshake", method: "POST", path: "/v1/auth/client-proof/handshake", authProfile: "clientProofV1", requiresSession: false, since: "0.1.0", requestType: "HandshakeRequest", responseType: "HandshakeResponse"),
        DeclaredOperation(id: "echo.send", method: "POST", path: "/v1/echo", authProfile: "clientProofV1", requiresSession: true, since: "0.1.0", requestType: "EchoRequest", responseType: "EchoResponse"),
        DeclaredOperation(id: "items.list", method: "POST", path: "/v1/items/list", authProfile: "clientProofV1", requiresSession: true, since: "0.1.0", requestType: "ListItemsRequest", responseType: "ListItemsResponse"),
        DeclaredOperation(id: "auth.enroll.register", method: "POST", path: "/_auth/register", authProfile: "none", requiresSession: false, since: "0.3.0", requestType: "RegisterRequest", responseType: "RegisterResponse"),
        DeclaredOperation(id: "auth.enroll.login", method: "POST", path: "/_auth/login", authProfile: "none", requiresSession: false, since: "0.3.0", requestType: "LoginRequest", responseType: "LoginResponse"),
        DeclaredOperation(id: "auth.enroll.oauthNative", method: "POST", path: "/_auth/oauth/{provider}/native", authProfile: "none", requiresSession: false, since: "0.3.0", requestType: "OauthNativeRequest", responseType: "OauthNativeResponse"),
        DeclaredOperation(id: "auth.keys.rotate", method: "POST", path: "/_auth/keys/rotate", authProfile: "clientProofV1", requiresSession: false, since: "0.3.0", requestType: "RotateKeyRequest", responseType: "RotateKeyResponse"),
        DeclaredOperation(id: "auth.keys.list", method: "POST", path: "/_auth/keys/list", authProfile: "clientProofV1", requiresSession: false, since: "0.4.1", requestType: "ListKeysRequest", responseType: "ListKeysResponse"),
        DeclaredOperation(id: "auth.keys.revoke", method: "POST", path: "/_auth/keys/revoke", authProfile: "clientProofV1", requiresSession: false, since: "0.4.1", requestType: "RevokeKeyRequest", responseType: "RevokeKeyResponse"),
        DeclaredOperation(id: "auth.keys.revokeAll", method: "POST", path: "/_auth/keys/revoke-all", authProfile: "clientProofV1", requiresSession: false, since: "0.4.1", requestType: "RevokeAllKeysRequest", responseType: "RevokeAllKeysResponse"),
        DeclaredOperation(id: "auth.device.start", method: "POST", path: "/_auth/device/start", authProfile: "none", requiresSession: false, since: "0.10.0", requestType: "StartDeviceAuthRequest", responseType: "StartDeviceAuthResponse"),
        DeclaredOperation(id: "auth.device.poll", method: "POST", path: "/_auth/device/poll", authProfile: "none", requiresSession: false, since: "0.10.0", requestType: "PollDeviceAuthRequest", responseType: "PollDeviceAuthResponse"),
        DeclaredOperation(id: "auth.device.info", method: "POST", path: "/_auth/device/info", authProfile: "clientProofV1", requiresSession: false, since: "0.10.0", requestType: "DeviceAuthInfoRequest", responseType: "DeviceAuthInfoResponse"),
        DeclaredOperation(id: "auth.device.approve", method: "POST", path: "/_auth/device/approve", authProfile: "clientProofV1", requiresSession: false, since: "0.10.0", requestType: "ApproveDeviceAuthRequest", responseType: "DeviceAuthInfoResponse"),
        DeclaredOperation(id: "auth.device.deny", method: "POST", path: "/_auth/device/deny", authProfile: "clientProofV1", requiresSession: false, since: "0.10.0", requestType: "DenyDeviceAuthRequest", responseType: nil),
    ]

    /// The bundle says what the table says — including the count, so an operation added
    /// upstream and never transcribed here fails rather than passing unexamined.
    func testTheBundleDeclaresExactlyTheTranscribedOperations() throws
    {
        let bundle = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json")))
        ).members()
        let declared = try bundle.list("operations").map { try $0.members() }

        XCTAssertEqual(declared.count, 16, "contract 0.10.0 declares sixteen operations")
        XCTAssertEqual(declared.count, Self.declaredOperations.count)

        for (entry, expected) in zip(declared, Self.declaredOperations)
        {
            XCTAssertEqual(try entry.text("id"), expected.id)
            XCTAssertEqual(try entry.text("method"), expected.method, expected.id)
            XCTAssertEqual(try entry.text("path"), expected.path, expected.id)
            XCTAssertEqual(try entry.text("authProfile"), expected.authProfile, expected.id)
            XCTAssertEqual(try entry.bool("requiresSession"), expected.requiresSession, expected.id)
            XCTAssertEqual(try entry.text("since"), expected.since, expected.id)
            XCTAssertEqual(try optionalText(entry, "requestType"), expected.requestType, expected.id)
            XCTAssertEqual(try optionalText(entry, "responseType"), expected.responseType, expected.id)
        }
    }

    /// And the generated descriptors say what the table says. `declaresResponse` is the
    /// field the execute path reads, so it is checked against the transcribed
    /// `responseType` rather than against the generated value it was emitted from.
    func testTheGeneratedDescriptorsMatchTheTranscribedOperations() throws
    {
        XCTAssertEqual(SPFNGeneratedOperations.all.count, Self.declaredOperations.count)

        for expected in Self.declaredOperations
        {
            let operation = try XCTUnwrap(
                SPFNGeneratedOperations.operation(id: expected.id),
                "\(expected.id) was not generated"
            )
            XCTAssertEqual(operation.method, expected.method, expected.id)
            XCTAssertEqual(operation.path, expected.path, expected.id)
            XCTAssertEqual(operation.authProfile, expected.authProfile, expected.id)
            XCTAssertEqual(operation.requiresSession, expected.requiresSession, expected.id)
            XCTAssertEqual(
                operation.declaresResponse,
                expected.responseType != nil,
                "\(expected.id) disagrees with the contract about whether it answers with a body"
            )
        }

        XCTAssertEqual(
            SPFNGeneratedOperations.all.filter { !$0.declaresResponse }.map(\.id),
            ["auth.device.deny"],
            "auth.device.deny is the contract's only operation that names no response type"
        )
    }

    /// A key an operation may legally omit, read as absent rather than as a failure.
    private func optionalText(_ members: [String: SPFNCanonicalValue], _ key: String) throws -> String?
    {
        guard members[key] != nil else { return nil }
        return try members.text(key)
    }

    func testRequestVectorsCanonicalizeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let requests = try fixture.list("requests")
        XCTAssertFalse(requests.isEmpty)

        for request in requests
        {
            let entry = try request.members()
            let name = try entry.text("name")
            let canonical = try roundTrip(type: try entry.text("type"), value: entry["value"]!)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical request bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical request digest differs for '\(name)'"
            )
        }
    }

    func testResponseVectorsDecodeAndReEncodeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let responses = try fixture.list("responses")
        XCTAssertFalse(responses.isEmpty)

        for response in responses
        {
            let entry = try response.members()
            let name = try entry.text("name")
            let wire = try SPFNCanonicalJSON.parse(try entry.text("wire"))
            let canonical = try roundTrip(type: try entry.text("type"), value: wire)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical response bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical response digest differs for '\(name)'"
            )
        }
    }

    /// The generated binding must refuse exactly what its own range excludes. The
    /// contract line is 0.x, so the neighbouring minor is a breaking change and not an
    /// additive one — this used to pass a 1.4.0 server because only majors were compared.
    func testAContractOutsideTheDeclaredRangeIsAnUpgradeError() throws
    {
        let binding = SPFNGeneratedContract.binding
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: binding.importedVersion))

        // A later patch on the pinned minor is additive and admitted: 0.10.1 would carry
        // everything 0.10.0 does. This is the direction the lower bound must not close.
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: "0.10.1"))
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: "0.10.9"))

        // The lower bound is the pinned version and not the minor floor. That rule was
        // written for the 0.4.1 pin, where 0.4.0 was the same minor and a major-and-minor
        // comparison would have admitted it — while the SDK called auth.keys.list,
        // auth.keys.revoke and auth.keys.revokeAll, which 0.4.1 added and a 0.4.0 server
        // does not serve. At this pin 0.10.0 is the minor's first release, so no
        // same-minor-lower-patch case exists to name; the rule is unchanged and the case
        // list simply has nothing to put there.
        //
        // The neighbouring minors are breaking in both directions on a 0.x line, so 0.9.x
        // sits below and 0.11.0 above. Contract 0.9.0 has none of the auth.device.*
        // operations this pin declares, and 0.9.x is where the device sign-in receipts
        // were taken — admitting it would let evidence about the old wire stand for the new.
        for version in ["0.1.0", "0.4.1", "0.6.0", "0.7.0", "0.8.0", "0.9.0", "0.9.9", "0.11.0", "1.0.0", "1.9.0", "2.0.0"]
        {
            XCTAssertThrowsError(try binding.requireSupported(serverContractVersion: version))
            { error in
                guard case SPFNDecodingError.unsupportedContractVersion(let found, let range) = error
                else
                {
                    return XCTFail("expected an upgrade error, got \(error)")
                }
                XCTAssertEqual(found, version)
                XCTAssertEqual(range, binding.admittedRange)
                // This pin is a release, so the two agree here. Both are built from the
                // pinned version and the same upper bound — the lock's range is checked
                // into that shape by the validator, and `admittedRange` computes it —
                // so they can only part on a pre-release pin, which admits one version.
                XCTAssertEqual(binding.admittedRange, binding.supportedRange)
            }
        }
    }

    /// Decodes a fixture value into the generated type it names, then re-encodes it.
    /// The switch is the one place a test has to know the contract's type names.
    private func roundTrip(type: String, value: SPFNCanonicalValue) throws -> SPFNCanonicalValue
    {
        switch type
        {
        case "HandshakeRequest":
            return try SPFNHandshakeRequest(canonical: value).canonicalValue()
        case "HandshakeResponse":
            return try SPFNHandshakeResponse(canonical: value).canonicalValue()
        case "EchoRequest":
            return try SPFNEchoRequest(canonical: value).canonicalValue()
        case "EchoResponse":
            return try SPFNEchoResponse(canonical: value).canonicalValue()
        case "ListItemsRequest":
            return try SPFNListItemsRequest(canonical: value).canonicalValue()
        case "ListItemsResponse":
            return try SPFNListItemsResponse(canonical: value).canonicalValue()
        default:
            XCTFail("fixture names an unknown type '\(type)'")
            throw ConformanceFailure.shape
        }
    }
}
