// SPFN Mobile — generated client conformance, Swift half of the parity gate.
//
// Every assertion here runs against generated code. If the generator changed shape, or
// the bundle changed and the clients were not regenerated, this suite is what notices.

import Foundation
import SPFNCore
import SPFNGenerated
import XCTest

final class OperationConformanceTests: XCTestCase
{
    func testGeneratedBindingMatchesTheLock() throws
    {
        let lock = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/upstream.lock.json")))
        ).members()
        let contract = try lock["contract"]!.members()

        XCTAssertEqual(SPFNGeneratedContract.binding.importedVersion, try contract.text("version"))
        XCTAssertEqual(SPFNGeneratedContract.binding.importedManifestSha256, try contract.text("manifestSha256"))

        // Codegen reads this range from the lock rather than from the bundle, so the
        // binding states the window this SDK admits and not the line upstream declares.
        // The two differ from 0.4.1 on: the bundle says ">=0.4.0 <0.5.0" because that is
        // the line, while the lock says ">=0.4.1 <0.5.0" because 0.4.1 added operations
        // a 0.4.0 server does not serve.
        XCTAssertEqual(SPFNGeneratedContract.binding.supportedRange, try contract.text("supportedRange"))
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMajor), try contract.number("major"))
        // The 0.x compatibility rule is decided from the major and the minor together,
        // so a generated binding that carried only the major would silently accept a
        // neighbouring minor the lock excludes.
        XCTAssertEqual(Int64(SPFNGeneratedContract.binding.supportedMinor), try contract.number("minor"))
    }

    func testGeneratedBindingDigestMatchesTheBundleOnDisk() throws
    {
        let bundle = try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json"))
        XCTAssertEqual(
            SPFNDigest.sha256Hex([UInt8](bundle)),
            SPFNGeneratedContract.binding.importedManifestSha256,
            "the generated header claims a digest the bundle does not have"
        )
    }

    /// The mirror of what this assertion used to say. While the bundle was hand-authored
    /// here, the test insisted the build must NOT claim an upstream export. The bundle is
    /// now generated by SPFN primitives, so the same question has the opposite answer —
    /// and it still has to be asked, because the origin string is what every consumer
    /// reads to decide whether the contract was verified against a server or against
    /// this repository's own opinion of one.
    func testTheBundleIsClaimedToBeAnUpstreamExport() throws
    {
        XCTAssertTrue(
            SPFNGeneratedContract.binding.isUpstreamExport,
            "the pinned bundle is an SPFN primitives export; a build that reports otherwise is reading a stale generated source"
        )
        XCTAssertEqual(SPFNGeneratedContract.binding.origin, "spfn-primitives-ci-export")
    }

    func testOperationDescriptorsMatchTheBundle() throws
    {
        let bundle = try SPFNCanonicalJSON.parse(
            [UInt8](try Data(contentsOf: Fixtures.repoRoot.appendingPathComponent("Contracts/spfn-mobile-contract.json")))
        ).members()

        let declared = try bundle.list("operations").map { try $0.members() }
        XCTAssertEqual(SPFNGeneratedOperations.all.count, declared.count)

        for entry in declared
        {
            let id = try entry.text("id")
            let operation = try XCTUnwrap(SPFNGeneratedOperations.operation(id: id), "\(id) was not generated")
            XCTAssertEqual(operation.method, try entry.text("method"))
            XCTAssertEqual(operation.path, try entry.text("path"))
            XCTAssertEqual(operation.authProfile, try entry.text("authProfile"))
            XCTAssertEqual(operation.requiresSession, try entry.bool("requiresSession"))

            // Every declared auth class resolves to a generated case; the generated
            // type is what lets the execute path fail closed on anything else.
            XCTAssertNotNil(
                SPFNGeneratedOperations.authClass(of: operation),
                "\(id) names an auth class the generated enum does not carry"
            )
        }

        XCTAssertNil(SPFNGeneratedOperations.operation(id: "no.such.operation"))
    }

    func testRequestVectorsCanonicalizeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let requests = try fixture.list("requests")
        XCTAssertFalse(requests.isEmpty)

        for request in requests
        {
            let entry = try request.members()
            let name = try entry.text("name")
            let canonical = try roundTrip(type: try entry.text("type"), value: entry["value"]!)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical request bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical request digest differs for '\(name)'"
            )
        }
    }

    func testResponseVectorsDecodeAndReEncodeIdentically() throws
    {
        let fixture = try Fixtures.load("request/operations.json").members()
        let responses = try fixture.list("responses")
        XCTAssertFalse(responses.isEmpty)

        for response in responses
        {
            let entry = try response.members()
            let name = try entry.text("name")
            let wire = try SPFNCanonicalJSON.parse(try entry.text("wire"))
            let canonical = try roundTrip(type: try entry.text("type"), value: wire)

            XCTAssertEqual(
                SPFNCanonicalJSON.encodeToString(canonical),
                try entry.text("canonical"),
                "canonical response bytes differ for '\(name)'"
            )
            XCTAssertEqual(
                SPFNDigest.sha256Hex(SPFNCanonicalJSON.encode(canonical)),
                try entry.text("sha256"),
                "canonical response digest differs for '\(name)'"
            )
        }
    }

    /// The generated binding must refuse exactly what its own range excludes. The
    /// contract line is 0.x, so the neighbouring minor is a breaking change and not an
    /// additive one — this used to pass a 1.4.0 server because only majors were compared.
    func testAContractOutsideTheDeclaredRangeIsAnUpgradeError() throws
    {
        let binding = SPFNGeneratedContract.binding
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: binding.importedVersion))

        // A later patch on the pinned minor is additive and admitted: 0.8.1 would carry
        // everything 0.8.0 does. This is the direction the lower bound must not close.
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: "0.8.1"))
        XCTAssertNoThrow(try binding.requireSupported(serverContractVersion: "0.8.9"))

        // The lower bound is the pinned version and not the minor floor. That rule was
        // written for the 0.4.1 pin, where 0.4.0 was the same minor and a major-and-minor
        // comparison would have admitted it — while the SDK called auth.keys.list,
        // auth.keys.revoke and auth.keys.revokeAll, which 0.4.1 added and a 0.4.0 server
        // does not serve. At this pin 0.8.0 is the minor's first release, so no
        // same-minor-lower-patch case exists to name; the rule is unchanged and the case
        // list simply has nothing to put there.
        //
        // The neighbouring minors are breaking in both directions on a 0.x line, so 0.7.x
        // sits below and 0.9.0 above. 0.6.0 is the previous pin, which this SDK must now
        // refuse: its grammar still declared `number` and its envelope still told the
        // decoder what to do with an unknown code, both of which 0.7.0 and 0.8.0 removed.
        for version in ["0.1.0", "0.4.1", "0.6.0", "0.6.9", "0.7.0", "0.9.0", "1.0.0", "1.8.0", "2.0.0"]
        {
            XCTAssertThrowsError(try binding.requireSupported(serverContractVersion: version))
            { error in
                guard case SPFNDecodingError.unsupportedContractVersion(let found, let range) = error
                else
                {
                    return XCTFail("expected an upgrade error, got \(error)")
                }
                XCTAssertEqual(found, version)
                XCTAssertEqual(range, binding.admittedRange)
                // This pin is a release, so the two agree here. Both are built from the
                // pinned version and the same upper bound — the lock's range is checked
                // into that shape by the validator, and `admittedRange` computes it —
                // so they can only part on a pre-release pin, which admits one version.
                XCTAssertEqual(binding.admittedRange, binding.supportedRange)
            }
        }
    }

    /// Decodes a fixture value into the generated type it names, then re-encodes it.
    /// The switch is the one place a test has to know the contract's type names.
    private func roundTrip(type: String, value: SPFNCanonicalValue) throws -> SPFNCanonicalValue
    {
        switch type
        {
        case "HandshakeRequest":
            return try SPFNHandshakeRequest(canonical: value).canonicalValue
        case "HandshakeResponse":
            return try SPFNHandshakeResponse(canonical: value).canonicalValue
        case "EchoRequest":
            return try SPFNEchoRequest(canonical: value).canonicalValue
        case "EchoResponse":
            return try SPFNEchoResponse(canonical: value).canonicalValue
        case "ListItemsRequest":
            return try SPFNListItemsRequest(canonical: value).canonicalValue
        case "ListItemsResponse":
            return try SPFNListItemsResponse(canonical: value).canonicalValue
        default:
            XCTFail("fixture names an unknown type '\(type)'")
            throw ConformanceFailure.shape
        }
    }
}
