// SPFN Mobile — generated client conformance, Kotlin half of the parity gate.
//
// Every assertion here runs against generated code. If the generator changed shape, or
// the bundle changed and the clients were not regenerated, this suite is what notices.

package xyz.superfunction.spfn.conformance

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import xyz.superfunction.spfn.core.SpfnCanonicalJson
import xyz.superfunction.spfn.core.SpfnCanonicalValue
import xyz.superfunction.spfn.core.SpfnDecodingException
import xyz.superfunction.spfn.core.SpfnDigest
import xyz.superfunction.spfn.generated.SpfnEchoRequest
import xyz.superfunction.spfn.generated.SpfnEchoResponse
import xyz.superfunction.spfn.generated.SpfnGeneratedContract
import xyz.superfunction.spfn.generated.SpfnGeneratedOperations
import xyz.superfunction.spfn.generated.SpfnHandshakeRequest
import xyz.superfunction.spfn.generated.SpfnHandshakeResponse
import xyz.superfunction.spfn.generated.SpfnListItemsRequest
import xyz.superfunction.spfn.generated.SpfnListItemsResponse

class OperationConformanceTest
{
    @Test
    fun generatedBindingMatchesTheLock()
    {
        val lock = SpfnCanonicalJson.parse(Fixtures.bytes("Contracts/upstream.lock.json")).members();
        val contract = lock.obj("contract");

        assertEquals(contract.text("version"), SpfnGeneratedContract.BINDING.importedVersion);
        assertEquals(contract.text("manifestSha256"), SpfnGeneratedContract.BINDING.importedManifestSha256);
        assertEquals(contract.text("supportedRange"), SpfnGeneratedContract.BINDING.supportedRange);
        assertEquals(contract.number("major"), SpfnGeneratedContract.BINDING.supportedMajor.toLong());
        // The 0.x compatibility rule is decided from the major and the minor together, so
        // a generated binding carrying only the major would silently accept a
        // neighbouring minor the lock excludes.
        assertEquals(contract.number("minor"), SpfnGeneratedContract.BINDING.supportedMinor.toLong());
    }

    @Test
    fun generatedBindingDigestMatchesTheBundleOnDisk()
    {
        assertEquals(
            "the generated header claims a digest the bundle does not have",
            SpfnGeneratedContract.BINDING.importedManifestSha256,
            SpfnDigest.sha256Hex(Fixtures.bytes("Contracts/spfn-mobile-contract.json"))
        );
    }

    /**
     * The mirror of what this assertion used to say. While the bundle was hand-authored
     * here, the test insisted the build must NOT claim an upstream export. The bundle is
     * now generated by SPFN primitives, so the same question has the opposite answer —
     * and it still has to be asked, because the origin string is what every consumer
     * reads to decide whether the contract was verified against a server or against this
     * repository's own opinion of one.
     */
    @Test
    fun theBundleIsClaimedToBeAnUpstreamExport()
    {
        assertTrue(
            "the pinned bundle is an SPFN primitives export; a build reporting otherwise is reading a stale generated source",
            SpfnGeneratedContract.BINDING.isUpstreamExport
        );
        assertEquals("spfn-primitives-ci-export", SpfnGeneratedContract.BINDING.origin);
    }

    @Test
    fun operationDescriptorsMatchTheBundle()
    {
        val bundle = SpfnCanonicalJson.parse(Fixtures.bytes("Contracts/spfn-mobile-contract.json")).members();
        val declared = bundle.list("operations").map { it.members() };
        assertEquals(declared.size, SpfnGeneratedOperations.all.size);

        for (entry in declared)
        {
            val id = entry.text("id");
            val operation = SpfnGeneratedOperations.operation(id);
            assertNotNull("$id was not generated", operation);
            assertEquals(entry.text("method"), operation?.method);
            assertEquals(entry.text("path"), operation?.path);
            assertEquals("clientProofV1", operation?.authProfile);
        }

        assertNull(SpfnGeneratedOperations.operation("no.such.operation"));
    }

    @Test
    fun requestVectorsCanonicalizeIdentically()
    {
        val fixture = Fixtures.load("request/operations.json").members();
        val requests = fixture.list("requests");
        assertTrue(requests.isNotEmpty());

        for (request in requests)
        {
            val entry = request.members();
            val name = entry.text("name");
            val canonical = roundTrip(entry.text("type"), requireNotNull(entry["value"]));

            assertEquals(
                "canonical request bytes differ for '$name'",
                entry.text("canonical"),
                SpfnCanonicalJson.encodeToString(canonical)
            );
            assertEquals(
                "canonical request digest differs for '$name'",
                entry.text("sha256"),
                SpfnDigest.sha256Hex(SpfnCanonicalJson.encode(canonical))
            );
        }
    }

    @Test
    fun responseVectorsDecodeAndReEncodeIdentically()
    {
        val fixture = Fixtures.load("request/operations.json").members();
        val responses = fixture.list("responses");
        assertTrue(responses.isNotEmpty());

        for (response in responses)
        {
            val entry = response.members();
            val name = entry.text("name");
            val canonical = roundTrip(entry.text("type"), SpfnCanonicalJson.parse(entry.text("wire")));

            assertEquals(
                "canonical response bytes differ for '$name'",
                entry.text("canonical"),
                SpfnCanonicalJson.encodeToString(canonical)
            );
            assertEquals(
                "canonical response digest differs for '$name'",
                entry.text("sha256"),
                SpfnDigest.sha256Hex(SpfnCanonicalJson.encode(canonical))
            );
        }
    }

    @Test
    fun aContractOutsideTheDeclaredRangeIsAnUpgradeError()
    {
        val binding = SpfnGeneratedContract.BINDING;
        binding.requireSupported(binding.importedVersion);

        for (version in listOf("0.2.0", "1.0.0", "1.4.0", "2.0.0"))
        {
            try
            {
                binding.requireSupported(version);
                fail("'$version' is outside '${binding.admittedRange}' and must be refused");
            }
            catch (failure: SpfnDecodingException)
            {
                assertEquals("CONTRACT_UNSUPPORTED", failure.code);
                assertTrue(
                    "the refusal must name the admitted range, not the declared one",
                    failure.message!!.contains(binding.admittedRange)
                );
            }
        }
    }

    /**
     * Decodes a fixture value into the generated type it names, then re-encodes it.
     * The `when` is the one place a test has to know the contract's type names.
     */
    private fun roundTrip(type: String, value: SpfnCanonicalValue): SpfnCanonicalValue = when (type)
    {
        "HandshakeRequest" -> SpfnHandshakeRequest.decode(value).canonicalValue()
        "HandshakeResponse" -> SpfnHandshakeResponse.decode(value).canonicalValue()
        "EchoRequest" -> SpfnEchoRequest.decode(value).canonicalValue()
        "EchoResponse" -> SpfnEchoResponse.decode(value).canonicalValue()
        "ListItemsRequest" -> SpfnListItemsRequest.decode(value).canonicalValue()
        "ListItemsResponse" -> SpfnListItemsResponse.decode(value).canonicalValue()
        else -> error("fixture names an unknown type '$type'")
    }
}
