// SPFN Mobile — generated client conformance, Kotlin half of the parity gate.
//
// Every assertion here runs against generated code. If the generator changed shape, or
// the bundle changed and the clients were not regenerated, this suite is what notices.

package xyz.superfunction.spfn.conformance

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import xyz.superfunction.spfn.core.SpfnCanonicalJson
import xyz.superfunction.spfn.core.SpfnCanonicalValue
import xyz.superfunction.spfn.core.SpfnDecodingException
import xyz.superfunction.spfn.core.SpfnDigest
import xyz.superfunction.spfn.generated.SpfnEchoRequest
import xyz.superfunction.spfn.generated.SpfnEchoResponse
import xyz.superfunction.spfn.generated.SpfnGeneratedAuthClass
import xyz.superfunction.spfn.generated.SpfnGeneratedContract
import xyz.superfunction.spfn.generated.SpfnGeneratedOperations
import xyz.superfunction.spfn.generated.SpfnHandshakeRequest
import xyz.superfunction.spfn.generated.SpfnHandshakeResponse
import xyz.superfunction.spfn.generated.SpfnListItemsRequest
import xyz.superfunction.spfn.generated.SpfnListItemsResponse

class OperationConformanceTest
{
    @Test
    fun generatedBindingMatchesTheLock()
    {
        val lock = SpfnCanonicalJson.parse(Fixtures.bytes("Contracts/upstream.lock.json")).members();
        val contract = lock.obj("contract");

        assertEquals(contract.text("version"), SpfnGeneratedContract.BINDING.importedVersion);
        assertEquals(contract.text("manifestSha256"), SpfnGeneratedContract.BINDING.importedManifestSha256);
        assertEquals(contract.text("supportedRange"), SpfnGeneratedContract.BINDING.supportedRange);
        assertEquals(contract.number("major"), SpfnGeneratedContract.BINDING.supportedMajor.toLong());
        // The 0.x compatibility rule is decided from the major and the minor together, so
        // a generated binding carrying only the major would silently accept a
        // neighbouring minor the lock excludes.
        assertEquals(contract.number("minor"), SpfnGeneratedContract.BINDING.supportedMinor.toLong());
    }

    @Test
    fun generatedBindingDigestMatchesTheBundleOnDisk()
    {
        assertEquals(
            "the generated header claims a digest the bundle does not have",
            SpfnGeneratedContract.BINDING.importedManifestSha256,
            SpfnDigest.sha256Hex(Fixtures.bytes("Contracts/spfn-mobile-contract.json"))
        );
    }

    /**
     * The mirror of what this assertion used to say. While the bundle was hand-authored
     * here, the test insisted the build must NOT claim an upstream export. The bundle is
     * now generated by SPFN primitives, so the same question has the opposite answer —
     * and it still has to be asked, because the origin string is what every consumer
     * reads to decide whether the contract was verified against a server or against this
     * repository's own opinion of one.
     */
    @Test
    fun theBundleIsClaimedToBeAnUpstreamExport()
    {
        assertTrue(
            "the pinned bundle is an SPFN primitives export; a build reporting otherwise is reading a stale generated source",
            SpfnGeneratedContract.BINDING.isUpstreamExport
        );
        assertEquals("spfn-primitives-ci-export", SpfnGeneratedContract.BINDING.origin);
    }

    @Test
    fun operationDescriptorsMatchTheBundle()
    {
        val bundle = SpfnCanonicalJson.parse(Fixtures.bytes("Contracts/spfn-mobile-contract.json")).members();
        val declared = bundle.list("operations").map { it.members() };
        assertEquals(declared.size, SpfnGeneratedOperations.all.size);

        for (entry in declared)
        {
            val id = entry.text("id");
            val operation = SpfnGeneratedOperations.operation(id);
            assertNotNull("$id was not generated", operation);
            assertEquals(entry.text("method"), operation?.method);
            assertEquals(entry.text("path"), operation?.path);
            assertEquals(entry.text("authProfile"), operation?.authProfile);
            assertEquals(entry.bool("requiresSession"), operation?.requiresSession);

            // Every declared auth class resolves to a generated case; the generated
            // type is what lets the execute path fail closed on anything else.
            assertNotNull(
                "$id names an auth class the generated enum does not carry",
                operation?.let { SpfnGeneratedAuthClass.of(it) }
            );
        }

        assertNull(SpfnGeneratedOperations.operation("no.such.operation"));
    }

    @Test
    fun requestVectorsCanonicalizeIdentically()
    {
        val fixture = Fixtures.load("request/operations.json").members();
        val requests = fixture.list("requests");
        assertTrue(requests.isNotEmpty());

        for (request in requests)
        {
            val entry = request.members();
            val name = entry.text("name");
            val canonical = roundTrip(entry.text("type"), requireNotNull(entry["value"]));

            assertEquals(
                "canonical request bytes differ for '$name'",
                entry.text("canonical"),
                SpfnCanonicalJson.encodeToString(canonical)
            );
            assertEquals(
                "canonical request digest differs for '$name'",
                entry.text("sha256"),
                SpfnDigest.sha256Hex(SpfnCanonicalJson.encode(canonical))
            );
        }
    }

    @Test
    fun responseVectorsDecodeAndReEncodeIdentically()
    {
        val fixture = Fixtures.load("request/operations.json").members();
        val responses = fixture.list("responses");
        assertTrue(responses.isNotEmpty());

        for (response in responses)
        {
            val entry = response.members();
            val name = entry.text("name");
            val canonical = roundTrip(entry.text("type"), SpfnCanonicalJson.parse(entry.text("wire")));

            assertEquals(
                "canonical response bytes differ for '$name'",
                entry.text("canonical"),
                SpfnCanonicalJson.encodeToString(canonical)
            );
            assertEquals(
                "canonical response digest differs for '$name'",
                entry.text("sha256"),
                SpfnDigest.sha256Hex(SpfnCanonicalJson.encode(canonical))
            );
        }
    }

    @Test
    fun aContractOutsideTheDeclaredRangeIsAnUpgradeError()
    {
        val binding = SpfnGeneratedContract.BINDING;
        binding.requireSupported(binding.importedVersion);

        // A later patch on the pinned minor is additive and admitted: 0.9.1 would carry
        // everything 0.9.0 does. This is the direction the lower bound must not close.
        binding.requireSupported("0.9.1");
        binding.requireSupported("0.9.9");

        // The lower bound is the pinned version and not the minor floor. That rule was
        // written for the 0.4.1 pin, where 0.4.0 was the same minor and a major-and-minor
        // comparison would have admitted it — while the SDK called auth.keys.list,
        // auth.keys.revoke and auth.keys.revokeAll, which 0.4.1 added and a 0.4.0 server
        // does not serve. At this pin 0.9.0 is the minor's first release, so no
        // same-minor-lower-patch case exists to name; the rule is unchanged and the case
        // list simply has nothing to put there.
        //
        // The neighbouring minors are breaking in both directions on a 0.x line, so 0.8.x
        // sits below and 0.10.0 above. Contract 0.8.0 has no core.time operation or clock
        // synchronization policy, so admitting it would reintroduce device wall-clock proofs.
        for (version in listOf("0.1.0", "0.4.1", "0.6.0", "0.7.0", "0.8.0", "0.8.9", "0.10.0", "1.0.0", "1.9.0", "2.0.0"))
        {
            try
            {
                binding.requireSupported(version);
                fail("'$version' is outside '${binding.admittedRange}' and must be refused");
            }
            catch (failure: SpfnDecodingException)
            {
                assertEquals("CONTRACT_UNSUPPORTED", failure.code);
                assertTrue(
                    "the refusal must name the admitted range, not the declared one",
                    failure.message!!.contains(binding.admittedRange)
                );
            }
        }
    }

    /**
     * Decodes a fixture value into the generated type it names, then re-encodes it.
     * The `when` is the one place a test has to know the contract's type names.
     */
    private fun roundTrip(type: String, value: SpfnCanonicalValue): SpfnCanonicalValue = when (type)
    {
        "HandshakeRequest" -> SpfnHandshakeRequest.decode(value).canonicalValue()
        "HandshakeResponse" -> SpfnHandshakeResponse.decode(value).canonicalValue()
        "EchoRequest" -> SpfnEchoRequest.decode(value).canonicalValue()
        "EchoResponse" -> SpfnEchoResponse.decode(value).canonicalValue()
        "ListItemsRequest" -> SpfnListItemsRequest.decode(value).canonicalValue()
        "ListItemsResponse" -> SpfnListItemsResponse.decode(value).canonicalValue()
        else -> error("fixture names an unknown type '$type'")
    }
}
