// SPFN Mobile — what one invocation of the generator refuses, and what a write really does.
//
// Everything here is about the CALL rather than about the spec: the arguments a target is
// parsed out of, the three words a mode can be, the place a spec is read from, and the two
// modes themselves. None of it had a reader. `Target.parse` refuses five different mistakes
// and every one of them was a line nothing executed; `write` and `verify` were reachable
// only through Gradle, which runs them against the real tree and therefore can only ever say
// that the checked-in output is up to date.
//
// The write case is the one worth the fixture. It builds a repository root of its own — the
// lock, the bundle the lock points at, and the spec — writes into it, verifies what it
// wrote, edits one generated byte and requires the second verify to fail. That is the loop
// the two Gradle tasks are, end to end, and it had never been run in a test at all.

package xyz.superfunction.spfn.uicodegen

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Assume.assumeFalse
import org.junit.Test

class InvocationTest
{
    private val repoRoot = File("../..")

    private val specPath = "examples/ui-spec"

    /** A complete, legal argument list, which every case below breaks exactly one thing in. */
    private val arguments = listOf(
        "--target=probe",
        "--swift-root=Probe/Generated",
        "--kotlin-root=probe/kotlin/generated",
        "--kotlin-package=probe.generated",
        "--app-id=probe.app",
        "--generate-task=:ui-codegen:spfnGenerateProbeUi",
        "--verify-task=:ui-codegen:spfnProbeUiVerify"
    )

    private fun assertRefused(arguments: List<String>, expected: String)
    {
        try
        {
            Target.parse(arguments);
            fail("a target argument list was accepted that must be refused: $expected");
        }
        catch (failure: RuntimeException)
        {
            val message = failure.message ?: "";
            assertTrue("refused, but not on '$expected': $message", message.contains(expected));
        }
    }

    /**
     * The control: every field is read off the arguments rather than remembered.
     *
     * Read first, because each case below is a claim about ONE argument and a parse that
     * answered the same target whatever it was given would pass all five of them.
     */
    @Test
    fun `a complete argument list is read field by field`()
    {
        val target = Target.parse(arguments + listOf("--table-root=probe/cases", "--flows=approveDevice", "--runner-readouts=true"));

        assertEquals("probe", target.name);
        assertEquals("Probe/Generated", target.swiftRoot);
        assertEquals("probe/kotlin/generated", target.kotlinRoot);
        assertEquals("probe.generated", target.kotlinPackage);
        assertEquals("probe.app", target.appId);
        assertEquals("probe/cases", target.tableRoot);
        assertEquals(setOf("approveDevice"), target.flows);
        assertEquals(true, target.runnerReadouts);
        assertEquals(":ui-codegen:spfnGenerateProbeUi", target.generateTask);
        assertEquals(":ui-codegen:spfnProbeUiVerify", target.verifyTask);

        // The three optional keys are optional, and absent is not empty: no table, every
        // flow, no readouts.
        val plain = Target.parse(arguments);
        assertEquals(null, plain.tableRoot);
        assertEquals(null, plain.flows);
        assertEquals(false, plain.runnerReadouts);
    }

    /**
     * `--flows=` with nothing after it is a missing value, not an empty set.
     *
     * The empty set names no flow the spec does not declare, so `Spec.narrowedTo` has nothing
     * to refuse in it: the run emitted an app with no screens at all, reported success, and
     * deleted every file of the app that was there as a leftover from a spec nobody has. The
     * other keys have treated an empty value as missing since `required` was written.
     */
    @Test
    fun `an empty --flows is refused the way an empty required key is`()
    {
        assertRefused(arguments + "--flows=", "--flows is written with no flow name in it");
        assertRefused(arguments + "--flows=,  ,", "--flows is written with no flow name in it");
        assertRefused(
            arguments.filterNot { it.startsWith("--app-id") } + "--app-id=",
            "the target names no --app-id"
        );
    }

    @Test
    fun `an argument that is not a key-value pair, or names an unknown key, is refused`()
    {
        assertRefused(arguments + "target=example", "target argument 'target=example' is not --key=value");
        assertRefused(arguments + "--table-root", "target argument '--table-root' is not --key=value");
        assertRefused(arguments + "--kotlin-packge=probe", "unknown target argument '--kotlin-packge'");
    }

    @Test
    fun `a required target key that is absent is named in the refusal`()
    {
        listOf("--target", "--swift-root", "--kotlin-root", "--kotlin-package", "--app-id",
            "--generate-task", "--verify-task").forEach { key ->
            assertRefused(arguments.filterNot { it.startsWith("$key=") }, "the target names no $key");
        };
    }

    /**
     * `--runner-readouts` takes two words, and every other one is a refusal.
     *
     * Coerced to false, `--runner-readouts=yes` emits a scaffold whose cells cannot be run,
     * and the first evidence of it is fourteen Maestro flows timing out.
     */
    @Test
    fun `a runner-readouts value that is neither word is refused`()
    {
        assertRefused(arguments + "--runner-readouts=yes", "--runner-readouts is 'yes'; it must be true or false");
        assertEquals(false, Target.parse(arguments + "--runner-readouts=false").runnerReadouts);
    }

    // ---- the invocation itself -----------------------------------------------

    private fun assertExecuteRefused(arguments: List<String>, expected: String)
    {
        try
        {
            execute(arguments.toTypedArray());
            fail("an invocation was accepted that must be refused: $expected");
        }
        catch (failure: RuntimeException)
        {
            val message = failure.message ?: "";
            assertTrue("refused, but not on '$expected': $message", message.contains(expected));
        }
    }

    @Test
    fun `an invocation missing its three positional arguments answers with the usage line`()
    {
        assertExecuteRefused(
            listOf(repoRoot.path, specPath),
            "usage: ui-codegen <repoRoot> <specFileOrDirectory> <write|verify>"
        );

        // The usage line names every flag a run really needs, including the two that are
        // required and were missing from it: a reader who copies it gets a working call.
        assertExecuteRefused(emptyList(), "--generate-task=<task> --verify-task=<task>");
    }

    @Test
    fun `a mode that is neither write nor verify is refused`()
    {
        assertExecuteRefused(
            listOf(repoRoot.path, specPath, "regenerate") + arguments,
            "unknown mode 'regenerate'; expected write or verify"
        );
    }

    /**
     * A spec path is a place, and both ways it can fail to be one are refused by name.
     *
     * A path that is nothing at all, and a directory that holds no piece of a spec — the
     * second is the one a person meets, by pointing the generator at the repository root or
     * at a directory whose documents have not been written yet.
     */
    @Test
    fun `a spec path that is nothing, and a directory with no spec in it, are refused`()
    {
        assertExecuteRefused(
            listOf(repoRoot.path, "examples/no-such-spec", "verify") + arguments,
            "missing examples/no-such-spec"
        );

        val empty = "tools/ui-codegen/build/empty-spec";
        File(repoRoot, empty).deleteRecursively();
        File(repoRoot, empty).mkdirs();
        assertExecuteRefused(
            listOf(repoRoot.path, empty, "verify") + arguments,
            "$empty holds no spec: a directory spec is its *.json files"
        );
    }

    /**
     * The whole loop, in a tree of this suite's own: write, verify, edit one byte, verify.
     *
     * Every other case in this repository reads `generate`, which returns a map and touches
     * nothing. What that cannot say is whether the files reach the disk, whether `verify`
     * compares what `write` wrote, or whether an edited generated file is caught — which is
     * the entire claim the two Gradle tasks make.
     *
     * The root is a fixture root and the target's own roots are inside it, so nothing this
     * case writes or deletes is outside the module's build directory. The file left BESIDE
     * the output is what says so: `keep.txt` sits in the fixture root, is not under any
     * directory the target owns, and is still there at the end.
     */
    @Test
    fun `write puts the scaffold on disk, verify reads it back, and one edited byte fails`()
    {
        val root = fixtureRoot("write-round-trip");
        val keep = File(root, "keep.txt");
        keep.writeText("not this generator's file\n");

        val call = listOf(
            "--target=probe",
            "--swift-root=out/Generated",
            "--kotlin-root=out/kotlin",
            "--kotlin-package=probe.generated",
            "--app-id=probe.app",
            "--generate-task=:ui-codegen:spfnGenerateProbeUi",
            "--verify-task=:ui-codegen:spfnProbeUiVerify"
        );

        execute((listOf(root.path, specPath, "write") + call).toTypedArray());
        val written = File(root, "out/Generated/Screens/EnterCodeModel.swift");
        assertTrue("write wrote no model file", written.isFile);

        // What was written verifies. This is the assertion the Gradle tasks make, made
        // against a tree this case produced rather than against the checked-in one.
        execute((listOf(root.path, specPath, "verify") + call).toTypedArray());

        // One byte of one generated file, which is exactly what a hand edit looks like.
        written.writeText(written.readText().replace("public final class", "internal final class"));
        assertExecuteRefused(
            listOf(root.path, specPath, "verify") + call,
            "out/Generated/Screens/EnterCodeModel.swift differs from freshly generated output"
        );

        // A file the generator did not write, in a directory it does not own, survives.
        assertTrue("the run reached outside the directories it owns", keep.isFile);
    }

    /**
     * A stale file the run could not delete stops the run rather than being reported gone.
     *
     * `File.delete` answers false for a file it did not remove, and the answer was dropped:
     * `removed <path>` was printed either way, so the next `verify` failed on a leftover the
     * previous run had said it deleted — a contradiction between two runs of the same tool,
     * with the evidence pointing at the wrong one.
     *
     * The way to make a delete fail without root is a directory with no write permission,
     * which a process running AS root can delete from anyway. So the case measures whether
     * the trick worked before it asserts anything about it.
     */
    @Test
    fun `a stale file that cannot be deleted stops the write`()
    {
        val root = fixtureRoot("undeletable");
        val call = listOf(
            "--target=probe",
            "--swift-root=out/Generated",
            "--kotlin-root=out/kotlin",
            "--kotlin-package=probe.generated",
            "--app-id=probe.app",
            "--generate-task=:ui-codegen:spfnGenerateProbeUi",
            "--verify-task=:ui-codegen:spfnProbeUiVerify"
        );
        execute((listOf(root.path, specPath, "write") + call).toTypedArray());

        val views = File(root, "out/Generated/Views");
        val ghost = File(views, "GhostView.swift");
        ghost.writeText("// left behind by a spec that no longer declares it\n");
        views.setWritable(false);
        try
        {
            assumeFalse("this JVM deletes from a read-only directory", ghost.delete());
            assertExecuteRefused(
                listOf(root.path, specPath, "write") + call,
                "could not remove out/Generated/Views/GhostView.swift"
            );
        }
        finally
        {
            views.setWritable(true);
        }
    }

    /**
     * A repository root holding only what a run reads: the lock, the bundle it points at,
     * and the spec. Built rather than pointed at the real tree, because `write` writes.
     */
    private fun fixtureRoot(name: String): File
    {
        val root = File(repoRoot, "tools/ui-codegen/build/$name");
        root.deleteRecursively();
        val lock = File(repoRoot, "Contracts/upstream.lock.json");
        val bundlePath = Regex("\"bundlePath\": \"([^\"]+)\"").find(lock.readText())?.groupValues?.get(1)
            ?: error("the lock names no bundlePath");
        listOf("Contracts/upstream.lock.json", bundlePath, specPath).forEach { relative ->
            val destination = File(root, relative);
            destination.parentFile?.mkdirs();
            val source = File(repoRoot, relative);
            if (source.isDirectory)
            {
                source.copyRecursively(destination, overwrite = true);
            }
            else
            {
                source.copyTo(destination, overwrite = true);
            }
        };
        return root;
    }
}
