// The app-contract type table, run against real wire bytes — Kotlin half.
//
// `appcontract/` is generated by `:contract-codegen:spfnAppContractFixtureGenerate` from the
// invented document in tools/contract-codegen/src/test/resources/app-contract. Every
// expected value below is written by hand from docs/architecture/app-contract-codegen.md,
// not read back from the generator (P10). Tests/SPFNCoreTests/AppContractFixtureTests.swift
// holds the same rows with the same literals; a row added here is added there.

package xyz.superfunction.spfn.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertSame
import org.junit.Assert.fail
import org.junit.Test
import xyz.superfunction.spfn.core.appcontract.FixtureAPI
import xyz.superfunction.spfn.core.appcontract.FixtureAPISupport
import xyz.superfunction.spfn.core.appcontract.GetItemResponse
import xyz.superfunction.spfn.core.appcontract.GetItemResponseItemKind
import xyz.superfunction.spfn.core.appcontract.GetItemResponseItemLabels
import xyz.superfunction.spfn.core.appcontract.GetItemResponseItemMarker
import xyz.superfunction.spfn.core.appcontract.ListItemsQuerySort
import xyz.superfunction.spfn.core.appcontract.ListItemsResponse
import xyz.superfunction.spfn.core.appcontract.PutItemNoteBody
import xyz.superfunction.spfn.core.appcontract.PutItemNoteBodyAttachmentsItem
import xyz.superfunction.spfn.core.appcontract.PutItemNoteBodyMode

class AppContractFixtureTest
{
    /** Every required key present; `title` and `labels` present-null; no optional key. */
    private val item = """
        {"default":"d","id":"i1","in":true,"kind":"in_review","labels":null,"lastEditor":null,
         "marker":"v1","owner":{"displayName":"Ann","id":"u1"},"pinned":false,"rank":3,
         "reviewers":[{"displayName":"Bo","id":"u2"}],"tags":["a","b"],"title":null,
         "updatedAt":"2026-09-27T10:00:00.000Z"}
    """.trimIndent()

    private fun getItem(itemJson: String): GetItemResponse =
        FixtureAPI.getItem("i1").decode(SpfnCanonicalJson.parse("""{"item":$itemJson,"matrix":[[1,2],[]]}"""))

    private fun assertDecodeFails(code: String, itemJson: String)
    {
        try
        {
            getItem(itemJson);
            fail("decoded an item the table says must fail with $code");
        }
        catch (failure: SpfnDecodingException)
        {
            assertEquals(code, failure.code);
        }
    }

    // ---- T1–T7, T11–T13, F4: the shapes ------------------------------------

    @Test
    fun `T1 T2 T4 T6 T7 T13 scalars, arrays and nested objects decode as declared`()
    {
        val decoded = getItem(item).item;
        assertEquals("i1", decoded.id);
        assertEquals(3L, decoded.rank);
        assertEquals(false, decoded.pinned);
        assertEquals(listOf("a", "b"), decoded.tags);
        assertEquals("Ann", decoded.owner.displayName);
        assertEquals("u2", decoded.reviewers.single().id);
        assertEquals(listOf(listOf(1L, 2L), emptyList<Long>()), getItem(item).matrix);
    }

    @Test
    fun `F4 a timestamp stays the string the server sent`()
    {
        assertEquals("2026-09-27T10:00:00.000Z", getItem(item).item.updatedAt);
    }

    @Test
    fun `T11 a known constant decodes to its case`()
    {
        assertSame(GetItemResponseItemKind.InReview, getItem(item).item.kind);
    }

    @Test
    fun `T12 a lone constant decodes to its one case`()
    {
        assertSame(GetItemResponseItemMarker.V1, getItem(item).item.marker);
    }

    @Test
    fun `keyword property names read their wire names`()
    {
        val decoded = getItem(item).item;
        assertEquals("d", decoded.default);
        assertEquals(true, decoded.`in`);
    }

    // ---- F1–F3: a newer server ---------------------------------------------

    @Test
    fun `F1 an unknown constant decodes as Unknown and keeps the raw value`()
    {
        val decoded = getItem(item.replace("\"in_review\"", "\"archived\"")).item;
        assertEquals(GetItemResponseItemKind.Unknown("archived"), decoded.kind);
        assertEquals("archived", decoded.kind.wireValue);
    }

    @Test
    fun `F1 an unknown constant in a nullable set decodes as Unknown too`()
    {
        val decoded = getItem(item.replace("\"labels\":null", "\"labels\":\"green\"")).item;
        assertEquals(GetItemResponseItemLabels.Unknown("green"), decoded.labels);
    }

    @Test
    fun `F2 an extra field is ignored`()
    {
        assertEquals("i1", getItem(item.replace("{\"default\"", "{\"addedLater\":{\"x\":[1]},\"default\"")).item.id);
    }

    @Test
    fun `F3 T9 a missing optional field decodes as null`()
    {
        val decoded = getItem(item).item;
        assertNull(decoded.note);
        assertNull(decoded.archivedAt);
        assertNull(ListItemsResponse.decode(SpfnCanonicalJson.parse("""{"items":[]}""")).nextCursor);
    }

    // ---- T8–T10: required, nullable, both ----------------------------------

    @Test
    fun `T8 a required nullable field sent as null decodes as null`()
    {
        assertNull(getItem(item).item.title);
        assertNull(getItem(item).item.lastEditor);
    }

    @Test
    fun `T8 a required nullable field sent as a value decodes as that value`()
    {
        assertEquals("Plan", getItem(item.replace("\"title\":null", "\"title\":\"Plan\"")).item.title);
    }

    @Test
    fun `T8 a required nullable field left out fails as MISSING_FIELD`()
    {
        assertDecodeFails("MISSING_FIELD", item.replace("\"title\":null,", ""));
    }

    @Test
    fun `T9 an optional field sent as null decodes as null`()
    {
        assertNull(getItem(item.replace("{\"default\"", "{\"note\":null,\"default\"")).item.note);
    }

    @Test
    fun `T10 an optional nullable field decodes null and absence alike`()
    {
        assertNull(getItem(item.replace("{\"default\"", "{\"archivedAt\":null,\"default\"")).item.archivedAt);
        assertEquals("x", getItem(item.replace("{\"default\"", "{\"archivedAt\":\"x\",\"default\"")).item.archivedAt);
    }

    @Test
    fun `a required non-null field sent as null fails as MISSING_FIELD`()
    {
        assertDecodeFails("MISSING_FIELD", item.replace("\"id\":\"i1\"", "\"id\":null"));
    }

    @Test
    fun `a wrong type fails as TYPE_MISMATCH`()
    {
        assertDecodeFails("TYPE_MISMATCH", item.replace("\"rank\":3", "\"rank\":\"3\""));
    }

    // ---- T14–T19: the calls ------------------------------------------------

    @Test
    fun `T14 path parameters are substituted percent-encoded`()
    {
        assertEquals("/v1/items/i1", FixtureAPI.getItem("i1").operation.path);
        assertEquals("/v1/items/a%20b%2Fc%C3%BC~._-", FixtureAPI.getItem("a b/cü~._-").operation.path);
        assertEquals("/v1/items/%2E%2E/notes/7", FixtureAPI.putItemNote("..", 7).operation.path);
        assertEquals("%2E", FixtureAPISupport.pathSegment("."));
    }

    @Test
    fun `T15 query arguments are appended in name order and null ones left out`()
    {
        assertEquals("/v1/items?limit=10", FixtureAPI.listItems(limit = 10).operation.path);
        assertEquals(
            "/v1/items?archived=true&cursor=a%26b%3Dc&limit=10&sort=newest",
            FixtureAPI.listItems(archived = true, cursor = "a&b=c", limit = 10, sort = ListItemsQuerySort.Newest).operation.path
        );
    }

    @Test
    fun `G5 the descriptor carries auth and session exactly as the document states`()
    {
        val getItem = FixtureAPI.getItem("i1").operation;
        assertEquals(SpfnOperation("getItem", "GET", "/v1/items/i1", "clientProofV1", false, true), getItem);
        val listItems = FixtureAPI.listItems(limit = 1).operation;
        assertEquals(SpfnOperation("listItems", "GET", "/v1/items?limit=1", "none", false, true), listItems);
        val putItemNote = FixtureAPI.putItemNote("i1", 2).operation;
        assertEquals(SpfnOperation("putItemNote", "PUT", "/v1/items/i1/notes/2", "clientProofV1", true, false), putItemNote);
    }

    @Test
    fun `T16 T8 T9 a body writes an explicit null for a required nullable field and omits an absent optional one`()
    {
        val body = PutItemNoteBody(
            attachments = listOf(PutItemNoteBodyAttachmentsItem(name = "a.txt", size = 12, `object` = true)),
            label = null,
            mode = PutItemNoteBodyMode.Append,
            text = "hello"
        );
        assertEquals(
            """{"attachments":[{"name":"a.txt","object":true,"size":12}],"label":null,"mode":"append","text":"hello"}""",
            SpfnCanonicalJson.encodeToString(FixtureAPI.putItemNote("i1", 1).encode(body))
        );
    }

    @Test
    fun `T17 a call without a request sends an empty object`()
    {
        assertEquals(SpfnCanonicalValue.Obj(emptyMap()), FixtureAPI.getItem("i1").encode(Unit));
    }

    @Test
    fun `T19 a bodyless response decodes to SpfnNoResponse`()
    {
        assertSame(SpfnNoResponse, FixtureAPI.putItemNote("i1", 1).decode(SpfnCanonicalValue.Obj(emptyMap())));
    }
}
