// The app-contract type table, run against real wire bytes — Swift half.
//
// `AppContractFixture/` is generated by `:contract-codegen:spfnAppContractFixtureGenerate`
// from the invented document in tools/contract-codegen/src/test/resources/app-contract.
// Every expected value below is written by hand from docs/architecture/app-contract-codegen.md
// (P10). android/spfn-core/src/test/.../AppContractFixtureTest.kt holds the same rows with
// the same literals; a row added here is added there.

import Foundation
import XCTest
@testable import SPFNCore

final class AppContractFixtureTests: XCTestCase
{
    /// Every required key present; `title` and `labels` present-null; no optional key.
    private let item = """
        {"default":"d","id":"i1","in":true,"kind":"in_review","labels":null,"lastEditor":null,
         "marker":"v1","owner":{"displayName":"Ann","id":"u1"},"pinned":false,"rank":3,
         "reviewers":[{"displayName":"Bo","id":"u2"}],"tags":["a","b"],"title":null,
         "updatedAt":"2026-09-27T10:00:00.000Z"}
        """

    private func getItem(_ itemJSON: String) throws -> FixtureAPI.GetItemResponse
    {
        try FixtureAPI.getItem(itemId: "i1").decode(SPFNCanonicalJSON.parse("{\"item\":\(itemJSON),\"matrix\":[[1,2],[]]}"))
    }

    private func assertDecodeFails(_ expected: SPFNDecodingError, _ itemJSON: String, file: StaticString = #filePath, line: UInt = #line)
    {
        do
        {
            _ = try getItem(itemJSON)
            XCTFail("decoded an item the table says must fail with \(expected)", file: file, line: line)
        }
        catch
        {
            XCTAssertEqual(error as? SPFNDecodingError, expected, file: file, line: line)
        }
    }

    // MARK: - T1–T7, T11–T13, F4: the shapes

    func testT1T2T4T6T7T13ScalarsArraysAndNestedObjectsDecodeAsDeclared() throws
    {
        let decoded = try getItem(item)
        XCTAssertEqual(decoded.item.id, "i1")
        XCTAssertEqual(decoded.item.rank, 3)
        XCTAssertEqual(decoded.item.pinned, false)
        XCTAssertEqual(decoded.item.tags, ["a", "b"])
        XCTAssertEqual(decoded.item.owner.displayName, "Ann")
        XCTAssertEqual(decoded.item.reviewers.map(\.id), ["u2"])
        XCTAssertEqual(decoded.matrix, [[1, 2], []])
    }

    func testF4ATimestampStaysTheStringTheServerSent() throws
    {
        XCTAssertEqual(try getItem(item).item.updatedAt, "2026-09-27T10:00:00.000Z")
    }

    func testT11AKnownConstantDecodesToItsCase() throws
    {
        XCTAssertEqual(try getItem(item).item.kind, .inReview)
    }

    func testT12ALoneConstantDecodesToItsOneCase() throws
    {
        XCTAssertEqual(try getItem(item).item.marker, .v1)
    }

    func testKeywordPropertyNamesReadTheirWireNames() throws
    {
        let decoded = try getItem(item).item
        XCTAssertEqual(decoded.`default`, "d")
        XCTAssertEqual(decoded.`in`, true)
    }

    // MARK: - F1–F3: a newer server

    func testF1AnUnknownConstantDecodesAsUnknownAndKeepsTheRawValue() throws
    {
        let decoded = try getItem(item.replacingOccurrences(of: "\"in_review\"", with: "\"archived\"")).item
        XCTAssertEqual(decoded.kind, .unknown("archived"))
        XCTAssertEqual(decoded.kind.wireValue, "archived")
    }

    func testF1AnUnknownConstantInANullableSetDecodesAsUnknownToo() throws
    {
        let decoded = try getItem(item.replacingOccurrences(of: "\"labels\":null", with: "\"labels\":\"green\"")).item
        XCTAssertEqual(decoded.labels, .unknown("green"))
    }

    func testF2AnExtraFieldIsIgnored() throws
    {
        let withExtra = item.replacingOccurrences(of: "{\"default\"", with: "{\"addedLater\":{\"x\":[1]},\"default\"")
        XCTAssertEqual(try getItem(withExtra).item.id, "i1")
    }

    func testF3T9AMissingOptionalFieldDecodesAsNil() throws
    {
        let decoded = try getItem(item).item
        XCTAssertNil(decoded.note)
        XCTAssertNil(decoded.archivedAt)
        XCTAssertNil(try FixtureAPI.ListItemsResponse(canonical: SPFNCanonicalJSON.parse("{\"items\":[]}")).nextCursor)
    }

    // MARK: - T8–T10: required, nullable, both

    func testT8ARequiredNullableFieldSentAsNullDecodesAsNil() throws
    {
        XCTAssertNil(try getItem(item).item.title)
        XCTAssertNil(try getItem(item).item.lastEditor)
    }

    func testT8ARequiredNullableFieldSentAsAValueDecodesAsThatValue() throws
    {
        XCTAssertEqual(try getItem(item.replacingOccurrences(of: "\"title\":null", with: "\"title\":\"Plan\"")).item.title, "Plan")
    }

    func testT8ARequiredNullableFieldLeftOutFailsAsMissingField()
    {
        assertDecodeFails(.missingField(path: "$.item.title"), item.replacingOccurrences(of: "\"title\":null,", with: ""))
    }

    func testT9AnOptionalFieldSentAsNullDecodesAsNil() throws
    {
        XCTAssertNil(try getItem(item.replacingOccurrences(of: "{\"default\"", with: "{\"note\":null,\"default\"")).item.note)
    }

    func testT10AnOptionalNullableFieldDecodesNullAndAbsenceAlike() throws
    {
        XCTAssertNil(try getItem(item.replacingOccurrences(of: "{\"default\"", with: "{\"archivedAt\":null,\"default\"")).item.archivedAt)
        XCTAssertEqual(try getItem(item.replacingOccurrences(of: "{\"default\"", with: "{\"archivedAt\":\"x\",\"default\"")).item.archivedAt, "x")
    }

    func testARequiredNonNullFieldSentAsNullFailsAsMissingField()
    {
        assertDecodeFails(.missingField(path: "$.item.id"), item.replacingOccurrences(of: "\"id\":\"i1\"", with: "\"id\":null"))
    }

    func testAWrongTypeFailsAsTypeMismatch()
    {
        assertDecodeFails(.typeMismatch(path: "$.item.rank", expected: "integer"), item.replacingOccurrences(of: "\"rank\":3", with: "\"rank\":\"3\""))
    }

    // MARK: - T14–T19: the calls

    func testT14PathParametersAreSubstitutedPercentEncoded()
    {
        XCTAssertEqual(FixtureAPI.getItem(itemId: "i1").operation.path, "/v1/items/i1")
        XCTAssertEqual(FixtureAPI.getItem(itemId: "a b/cü~._-").operation.path, "/v1/items/a%20b%2Fc%C3%BC~._-")
        XCTAssertEqual(FixtureAPI.putItemNote(itemId: "..", noteNumber: 7).operation.path, "/v1/items/%2E%2E/notes/7")
        XCTAssertEqual(FixtureAPI.pathSegment("."), "%2E")
    }

    func testT15QueryArgumentsAreAppendedInNameOrderAndNilOnesLeftOut()
    {
        XCTAssertEqual(FixtureAPI.listItems(limit: 10).operation.path, "/v1/items?limit=10")
        XCTAssertEqual(
            FixtureAPI.listItems(archived: true, cursor: "a&b=c", limit: 10, sort: .newest).operation.path,
            "/v1/items?archived=true&cursor=a%26b%3Dc&limit=10&sort=newest"
        )
    }

    func testG5TheDescriptorCarriesAuthAndSessionExactlyAsTheDocumentStates()
    {
        XCTAssertEqual(
            FixtureAPI.getItem(itemId: "i1").operation,
            SPFNOperation(id: "getItem", method: "GET", path: "/v1/items/i1", authProfile: "clientProofV1", requiresSession: false, declaresResponse: true)
        )
        XCTAssertEqual(
            FixtureAPI.listItems(limit: 1).operation,
            SPFNOperation(id: "listItems", method: "GET", path: "/v1/items?limit=1", authProfile: "none", requiresSession: false, declaresResponse: true)
        )
        XCTAssertEqual(
            FixtureAPI.putItemNote(itemId: "i1", noteNumber: 2).operation,
            SPFNOperation(id: "putItemNote", method: "PUT", path: "/v1/items/i1/notes/2", authProfile: "clientProofV1", requiresSession: true, declaresResponse: false)
        )
    }

    func testT16T8T9ABodyWritesAnExplicitNullAndOmitsAnAbsentOptionalField() throws
    {
        let body = FixtureAPI.PutItemNoteBody(
            attachments: [FixtureAPI.PutItemNoteBodyAttachmentsItem(name: "a.txt", object: true, size: 12)],
            label: nil,
            mode: .append,
            text: "hello"
        )
        XCTAssertEqual(
            SPFNCanonicalJSON.encodeToString(try XCTUnwrap(FixtureAPI.putItemNote(itemId: "i1", noteNumber: 1).encode(body))),
            "{\"attachments\":[{\"name\":\"a.txt\",\"object\":true,\"size\":12}],\"label\":null,\"mode\":\"append\",\"text\":\"hello\"}"
        )
    }

    func testT17ACallWithoutARequestEncodesNoBody() throws
    {
        XCTAssertNil(try FixtureAPI.getItem(itemId: "i1").encode(()))
    }

    func testT19ABodylessResponseDecodesToSPFNNoResponse() throws
    {
        XCTAssertEqual(try FixtureAPI.putItemNote(itemId: "i1", noteNumber: 1).decode(.object([:])), SPFNNoResponse.value)
    }
}
